language: java

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE phonebook;'
  - mysql -uroot phonebook < test_db.sql
  - mysql -e 'USE phonebook;'
  - mysql -e "CREATE USER 'admin'@'%' IDENTIFIED BY 'qwerty';"
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;"

script: gradle build jar

after_failure:
  - cat /home/travis/build/Synthwaver/Eltex/build/reports/findbugs/main.html